USE SCHOOL;
SELECT* FROM STUDENT;
SELECT STD_NAME,DOB FROM STUDENT;
SELECT*FROM STUDENT WHERE PERCENTAGE>=80;
SELECT STD_NAME,STREAM,PERCENTAGE  FROM STUDENT WHERE PERCENTAGE>=80;
SELECT * FROM STUDENT  WHERE STREAM="SCIENCE" AND PERCENTAGE>75;